{% set name = "snakeviz" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snakeviz-{{ version }}.tar.gz
  sha256: 7bfd00be7ae147eb4a170a471578e1cd3f41f803238958b6b8efcf2c698a6aa9

build:
  entry_points:
    - snakeviz = snakeviz.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - tornado >=2.0

test:
  imports:
    - snakeviz
  commands:
    - pip check
    - snakeviz --help
  requires:
    - pip

about:
  home: https://jiffyclub.github.io/snakeviz/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Web-based viewer for Python profiler output
  description: |
    SnakeViz is a browser based graphical viewer for the output of Python's
    cProfile module.
  doc_url: https://jiffyclub.github.io/snakeviz/
  dev_url: https://github.com/jiffyclub/snakeviz
